### ISSUE TITLE
训练代码中缺失文件共享

### ISSUE THREAD

**Issue by itcrazy0918** [LL4J/Filter4Jx#1]
请问Train_4.java训练代码中缺失的 ts.model、train.csv等文件能共享一下吗？

**Comment by huzpsb** [comment]
ts.model是你自己生成的：
https://github.com/LL4J/Filter4Jx/blob/main/src/nlp/test/BuildTokenizer_2.java#L20
train.csv也是
https://github.com/LL4J/Filter4Jx/blob/main/src/nlp/test/Split_3.java#L23

**Comment by huzpsb** [comment]
....服了你个老六
数据集在readme里面有超链接
点一下 谢谢
