### ISSUE TITLE
Java heap space

### ISSUE THREAD

**Issue by AzraelSSS** [LL4J/Filter4Jx#2]
您好,请问运行Train_4.java训练代码后显示:
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at huzpsb.ll4j.nlp.token.Tokenizer.tokenize(Tokenizer.java:31)
	at huzpsb.ll4j.nlp.test.Train_4.main(Train_4.java:34)
在这之前还有出现过这样的问题:
java: 无法将类 huzpsb.ll4j.model.Model中的方法 trainOn应用到给定类型;
  需要: huzpsb.ll4j.data.DataSet
  找到:    huzpsb.ll4j.data.DataSet,double
  原因: 实际参数列表和形式参数列表长度不同
COLD.csv keywords.txt都有,也都是从这个Filter4Jx的readme文档中获取的.
这些问题该如何解决?是我自己电脑的问题吗?

**Comment by huzpsb** [comment]
产生java.lang.OutOfMemoryError是因为内存爆了
请确保自己的机器是64位架构且安装了64位的java，插入了足够的内存条并正确地使用了Xmx指定Jvm能够使用的内存量。

第二个可以提供相关代码的截图吗，谢谢

**Comment by AzraelSSS** [comment]
感谢回复!
截了这几张图,您看一下还需要其他截图吗.
![fd7cf0ea832890523960c70a9d2dccf](https://github.com/LL4J/Filter4Jx/assets/167045098/d53832b6-bba1-4f56-a125-31b9d2776892)
![782f0e44738904d9e0d6ae83d2921e5](https://github.com/LL4J/Filter4Jx/assets/167045098/5c51e27a-22ce-438e-a945-f9462442fc23)
![e15fea6964cce3977c36fcc9876b8d7](https://github.com/LL4J/Filter4Jx/assets/167045098/dbd13670-a04d-4d24-b62c-f8b9f6eba9a3)

**Comment by huzpsb** [comment]
~~这么晚还不睡 修仙在呐？~~
只需删除第二个参数

**Comment by AzraelSSS** [comment]
双休日在家睡得晚,睡前看到邮箱回复就再运行了遍程序哈哈.
感谢回复,我去掉参数后就显示一个 Java heap space 了:
![b53f7d80e62a9f9e38af04f0a733091](https://github.com/LL4J/Filter4Jx/assets/167045098/96b9d21b-1425-49a0-8899-2416b21c6f62)
我的电脑是64位的,内存8G*2.
环境变量里这样设置了java的xmx等:
![b0d42a42ba44f1ddbd903497ac5320a](https://github.com/LL4J/Filter4Jx/assets/167045098/a587a1ca-788f-4445-b44f-08554a963d50)
请问是内存仍不够还是xmx设置错误或者其他问题?

**Comment by huzpsb** [comment]
> 双休日在家睡得晚,睡前看到邮箱回复就再运行了遍程序哈哈.
> 感谢回复,我去掉参数后就显示一个 Java heap space 了:
> ![b53f7d80e62a9f9e38af04f0a733091](https://github.com/LL4J/Filter4Jx/assets/167045098/96b9d21b-1425-49a0-8899-2416b21c6f62)
> 我的电脑是64位的,内存8G*2.
> 环境变量里这样设置了java的xmx等:
> ![b0d42a42ba44f1ddbd903497ac5320a](https://github.com/LL4J/Filter4Jx/assets/167045098/a587a1ca-788f-4445-b44f-08554a963d50)
> 请问是内存仍不够还是xmx设置错误或者其他问题?

可能是因为内存就是不够 我自己的电脑是128GB内存的（
考虑减小Tokenizer大小，删除部分语料，或者租个大内存的服务器运行？

**Comment by AzraelSSS** [comment]
OK,非常感谢!!!
